apiVersion: v1
kind: Service
metadata:
  name: {{ include "ServiceBusSessionScaler.fullname" . }}
  labels:
    {{- include "ServiceBusSessionScaler.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    {{- include "ServiceBusSessionScaler.selectorLabels" . | nindent 4 }}
